// server/ClientApp/src/solid-app.tsx
import "./styles.css";
import { render } from "solid-js/web";
import { Dashboard } from "./components/Dashboard";

// Map DOM element → SolidJS dispose function for clean unmounting
const disposers = new Map<Element, () => void>();

window.AppBridge = {
  mount(element: Element, _props: Record<string, unknown> = {}) {
    if (disposers.has(element)) return;
    const dispose = render(() => <Dashboard />, element);
    disposers.set(element, dispose);
  },
  unmount(element: Element) {
    disposers.get(element)?.();
    disposers.delete(element);
  },
};

declare global {
  interface Window {
    AppBridge: {
      mount(element: Element, props?: Record<string, unknown>): void;
      unmount(element: Element): void;
    };
  }
}

// server/ClientApp/src/react-app.tsx
import "./styles.css";
import { createRoot, type Root } from "react-dom/client";
import { Dashboard } from "./components/Dashboard";

// Map DOM element → React root so we can unmount cleanly
const roots = new Map<Element, Root>();

window.ReactBridge = {
  mount(element: Element, props: Record<string, unknown> = {}) {
    if (roots.has(element)) return;
    const root = createRoot(element);
    roots.set(element, root);
    root.render(<Dashboard {...(props as any)} />);
  },
  unmount(element: Element) {
    roots.get(element)?.unmount();
    roots.delete(element);
  },
};

declare global {
  interface Window {
    ReactBridge: {
      mount(element: Element, props?: Record<string, unknown>): void;
      unmount(element: Element): void;
    };
  }
}
